USE TCC;

INSERT INTO TB_PERFIL (ID, NAME_PERFIL) VALUES (1, "Gerente");
INSERT INTO TB_PERFIL (ID, NAME_PERFIL) VALUES (2, "Colaborador");



INSERT INTO TB_PRIORITY_LEVEL (ID, NAME_PRIORITY_LEVE) VALUES (1, "BAIXA");
INSERT INTO TB_PRIORITY_LEVEL (ID, NAME_PRIORITY_LEVE) VALUES (2, "MEDIA");
INSERT INTO TB_PRIORITY_LEVEL (ID, NAME_PRIORITY_LEVE) VALUES (3, "ALTA");

INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (1, "CRIADO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (2, "EM DESENVOLVIMENTO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (3, "EM TESTES");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (4, "FINALIZADO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (5, "ATIVO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (6, "ENCERRADO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (7, "ATRASADO");
INSERT INTO TB_STATUS (ID, NAME_STATUS) VALUES (8, "TESTADO");
